version: "3.8"
services:
  db:
    image: ankane/pgvector
    container_name: mem0_pgvector
    environment:
      POSTGRES_DB: mem0
      POSTGRES_USER: XXX
      POSTGRES_PASSWORD: XXX
    ports:
      - "5432:5432"
    volumes:
      - XXX:/var/lib/postgresql/data

  mcp-mem0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_mem0
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://XXX:XXX@db:5432/mem0
      LLM_PROVIDER: openai
      LLM_BASE_URL: https://api.siliconflow.cn/v1
      LLM_API_KEY: XXX
      LLM_CHOICE: Qwen/QwQ-32B
      EMBEDDING_MODEL_CHOICE: BAAI/bge-large-zh-v1.5

    depends_on:
      - db
    ports:
      - "8050:8050"